# Generated by Django 3.0.5 on 2020-04-19 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_comment_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment',
        ),
    ]
