# Generated by Django 3.0.5 on 2020-05-02 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_auto_20200430_1346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
