# Generated by Django 2.2.12 on 2020-06-19 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0019_favoritearticle_favoritecomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritearticle',
            old_name='article',
            new_name='favorite_article',
        ),
        migrations.RenameField(
            model_name='favoritearticle',
            old_name='user',
            new_name='favorite_article_user',
        ),
        migrations.RenameField(
            model_name='favoritecomment',
            old_name='comment',
            new_name='favorite_comment',
        ),
        migrations.RenameField(
            model_name='favoritecomment',
            old_name='user',
            new_name='favorite_comment_user',
        ),
    ]
