# Generated by Django 2.2.12 on 2020-06-19 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_auto_20200619_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritearticle',
            name='favorite_article_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_article', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favoritecomment',
            name='favorite_comment_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
