# Generated by Django 2.2.12 on 2020-06-19 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0022_auto_20200619_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritearticle',
            old_name='favorite_article',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='favoritearticle',
            old_name='favorite_article_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='favoritecomment',
            old_name='favorite_comment',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='favoritecomment',
            old_name='favorite_comment_user',
            new_name='user',
        ),
    ]
