# Generated by Django 2.2.12 on 2020-06-19 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0023_auto_20200619_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritearticle',
            name='article',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_article', to='article.Article'),
        ),
        migrations.AlterField(
            model_name='favoritecomment',
            name='comment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_comment', to='article.Comment'),
        ),
    ]
