# Generated by Django 2.2.12 on 2020-07-06 07:43

import article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0025_auto_20200621_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_media',
            field=models.ImageField(default='', null=True, upload_to=article.models.article_media_save_path),
        ),
    ]
