# Generated by Django 2.2.14 on 2020-07-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0026_article_article_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
