# Generated by Django 2.2.14 on 2020-07-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0027_article_posted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
