# Generated by Django 3.0.6 on 2020-05-15 15:38

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='introductionImage',
            field=models.ImageField(null=True, upload_to=account.models.introduction_image_save_path),
        ),
        migrations.AddField(
            model_name='profile',
            name='profileImage',
            field=models.ImageField(null=True, upload_to=account.models.profile_image_save_path),
        ),
    ]
