# Generated by Django 2.2.12 on 2020-05-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200516_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='introduction',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
