# Generated by Django 2.2.12 on 2020-05-18 11:43

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200518_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='introductionImage',
            field=models.ImageField(default='defaultBackground.jpg', null=True, upload_to=account.models.introduction_image_save_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profileImage',
            field=models.ImageField(default='defaultProfile.jpg', null=True, upload_to=account.models.profile_image_save_path),
        ),
    ]
