# Generated by Django 2.2.12 on 2020-05-23 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200518_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='introductionImage',
            new_name='backgroundImage',
        ),
    ]
