# Generated by Django 2.2.12 on 2020-06-06 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_relation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='backgroundImage',
            new_name='background_image',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='profileImage',
            new_name='profile_image',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
