# Generated by Django 2.2.12 on 2020-06-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200606_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='is_deleted',
            field=models.BooleanField(default=True),
        ),
    ]
