# Generated by Django 2.2.12 on 2020-06-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_relation_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
