# Generated by Django 2.2.12 on 2020-06-26 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20200607_0613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='is_deleted',
        ),
    ]
