# Generated by Django 2.2.12 on 2020-07-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20200702_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkroom',
            name='last_message',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
