# Generated by Django 2.2.12 on 2020-07-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_talkroom_last_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='body',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
