# Generated by Django 2.2.12 on 2020-07-03 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0005_remove_message_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talkroom',
            name='login_user',
        ),
        migrations.RemoveField(
            model_name='talkroom',
            name='talk_to',
        ),
        migrations.AlterField(
            model_name='message',
            name='talk_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='message.TalkRoom'),
        ),
        migrations.CreateModel(
            name='UserOwnTalkRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant', to=settings.AUTH_USER_MODEL)),
                ('talk_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='message.TalkRoom')),
            ],
        ),
    ]
