# Generated by Django 2.2.14 on 2020-07-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_auto_20200703_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='create_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
